# Generated by Django 3.1.7 on 2022-04-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_code', models.BigIntegerField()),
                ('short_name', models.CharField(default='Initials', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=300)),
            ],
        ),
    ]
