# Generated by Django 3.1.7 on 2022-04-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_list', models.JSONField()),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('marks_outof', models.CharField(default='Not Assigned yet!', max_length=30)),
                ('marks_obtained', models.CharField(default='0', max_length=30)),
                ('assignment_id', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-assignment_id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerd_course', models.ManyToManyField(to='database.Course')),
            ],
        ),
    ]
